// <auto-generated />
using Magazin.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magazin.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Magazin.Services.ProductAPI.Models.DTO.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("IMG_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IMG_URL = "https://dotnet6forfirstproj.blob.core.windows.net/magazinproject/chipso.png",
                            Price = 9500.0,
                            ProductCategory = 2,
                            ProductDescription = "LAY'S®— bu shunchaki chips emas!\\r\\n\\r\\nLAY'S® - bu mahsulotning yuqori sifati va mijozlar haqida g'amxo'rlikdir. Axir biz kartoshka chipslarini tayyorlash uchun eng yaxshi ingredientlar: yuqori PepsiCo standartlariga muvofiq yetishtirilgan rus kartoshkalari, tabiiy o'simlik moylari va xushbo’y ziravorlardan foydalanamiz.\\r\\n\\r\\nBiz kunni  yanada yorqinroq qilish uchun 10 yildan beri ilk bor mahsulot qadog’i dizaynini yangiladik!",
                            ProductName = "Lays Chips"
                        },
                        new
                        {
                            ProductId = 2,
                            IMG_URL = "https://dotnet6forfirstproj.blob.core.windows.net/magazinproject/cola.png",
                            Price = 12000.0,
                            ProductCategory = 2,
                            ProductDescription = "“Coca‑Cola” kompaniyasi tarixidagi eng mashhur ichimlik 1886-yilning 8-may kuni Jorjiya shtatining Atlanta shahrida dorixonachi-shifokor Jon Pamberton tomonidan kashf etilgan. ",
                            ProductName = "Coca-Cola"
                        },
                        new
                        {
                            ProductId = 3,
                            IMG_URL = "https://dotnet6forfirstproj.blob.core.windows.net/magazinproject/lipton.jpeg",
                            Price = 8000.0,
                            ProductCategory = 2,
                            ProductDescription = "Lipton — торговая марка чая, зарегистрированная Томасом Липтоном в Великобритании в 1890 году. В настоящее время принадлежит компании Unilever. Также до 1980-х в Великобритании существовала сеть супермаркетов Lipton, созданная в 1871 году тем же Томасом Липтоном.",
                            ProductName = "Lipton"
                        },
                        new
                        {
                            ProductId = 4,
                            IMG_URL = "https://dotnet6forfirstproj.blob.core.windows.net/magazinproject/snickers.jpg",
                            Price = 8000.0,
                            ProductCategory = 1,
                            ProductDescription = "Батончик шоколадный \"Snickers\" 50 гр",
                            ProductName = "Snickers Buton"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
